### ISSUE TITLE
It doesn't open for me. 

### ISSUE THREAD

**Issue by itzayanacobos01** [Rubiksman78/RenAI-Chat#3]
I have done everything on the instructions, but the .bat does not open. What can I do?

**Comment by Rubiksman78** [comment]
Can you try running it from a Command Prompt or Powershell and send the exact error returned?

**Comment by supeast** [comment]
If you are on windows, check the run.bat file. For me it was not pointing to the correct python folder, so I could not run the bat 
file.

**Comment by Rubiksman78** [comment]
> If you are on windows, check the run.bat file. For me it was not pointing to the correct python folder, so I could not run the bat file.

Normally python is built in `libs/pythonlib` if you downloaded the windows user version from the drive.
