### ISSUE TITLE
Support for AMD or Intel?

### ISSUE THREAD

**Issue by NintendoManiac64** [Rubiksman78/RenAI-Chat#5]
Like many other a Linux users, I tend to shy away from using Nvidia GPUs and greatly prefer using AMD or Intel GPUs.

Obviously CUDA is proprietary and Nvidia-only, so the question then is - does RenAI Chat support other APIs that aren't exclusive to Nvidia, e.g. OpenCL, Vulkan, ROCm, OneAPI, etc? (OpenCL in particular is getting a new lease on life as a vendor-neutral solution in the Linux world with the recent development of RustiCL; also, ROCm seems much more workstation and sever-focused with [poor support of consumer-focused hardware](https://github.com/RadeonOpenCompute/ROCm/issues/1378))

There's also the angle of the various hardware accelerators built into some of AMD's and Intel's newest CPUs (not a typo), specifically AMD's "Phoenix" and and Intel's "Sapphire Rapids", to help accelerate these sort of machine learning workloads.

**Comment by Rubiksman78** [comment]
The main issue is that it relies on many repositories that support only CUDA based libraries with Nvidia GPUs. Most of Machine Learning libraries directly use acceleration based on CUDA so it would be difficult to completely change these frameworks.

However, a PyTorch version seems to be available for ROCm only on Linux but I believe it might not be the intended behaviour to use, it might work maybe for simple features.
