### ISSUE TITLE
No module named 'TTS.vc'

### ISSUE THREAD

**Issue by nakumiayumu144** [Rubiksman78/RenAI-Chat#8]
![image](https://user-images.githubusercontent.com/127565115/227813727-11203aba-7071-4e00-af35-3f67e18ae2fb.png)

**Comment by Rubiksman78** [comment]
Did you clone the TTS repository and install the requirements?

**Comment by nakumiayumu144** [comment]
yes i have clone Tortoise-TTS and install requirements.txt

**Comment by Rubiksman78** [comment]
No this one isn't related to Tortoise-TTS but to CoquiAI-TTS, I think you might need to install it too because I haven't put the import in option.

**Comment by Rubiksman78** [comment]
It should be fixed now, try pulling the modifications and run it
