### ISSUE TITLE
AssertionError: Torch not compiled with CUDA enabled

### ISSUE THREAD

**Issue by nakumiayumu144** [Rubiksman78/RenAI-Chat#9]
![image](https://user-images.githubusercontent.com/127565115/228523410-574c6df3-fefa-4078-9b1e-39b27290f585.png)

**Comment by Rubiksman78** [comment]
Run `setup_gpu.bat` after you've setup CUDA, cudNN and stuff for using your GPU. Local chatbots need GPU to run for now.

**Comment by nakumiayumu144** [comment]
where is that?

**Comment by Rubiksman78** [comment]
Sorry I mixed up, did you install it with your own python or did you use the built in from the drive?

**Comment by nakumiayumu144** [comment]
What do you mean? Is it the CUDA?
![image](https://user-images.githubusercontent.com/127565115/228530743-23f1632b-a82d-4ad4-a37e-5d2134eb31f7.png)

**Comment by Rubiksman78** [comment]
Yes it is

**Comment by nakumiayumu144** [comment]
I already installed it
![image](https://user-images.githubusercontent.com/127565115/228544327-62f5917c-ad03-4f17-bbe3-b121d37009ea.png)

**Comment by Rubiksman78** [comment]
> Sorry I mixed up, did you install it with your own python or did you use the built in from the drive?

Can you answer this question too?

**Comment by nakumiayumu144** [comment]
I installed it on my own
![image](https://user-images.githubusercontent.com/127565115/228551508-b26df4f4-45de-4ea5-b30c-a7a01646b911.png)

**Comment by Rubiksman78** [comment]
Did you install torch version for CUDA ? I suggest you to look at the Python installation section on the README if you did the setup with your own python build.

**Comment by nakumiayumu144** [comment]
every time I change the version it is always incompatible with other modules
pip install --force torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cu117
![image](https://user-images.githubusercontent.com/127565115/228560368-3d4758c4-5b34-4c58-b6a0-82871b937528.png)

**Comment by Rubiksman78** [comment]
Just download torch as explained and run the game usually, don't pay attention to the warnings it should work.

**Comment by nakumiayumu144** [comment]
can u give me example for character json?
and where is the location save file i want to reset?

**Comment by Rubiksman78** [comment]
What do you mean by location save file?

There is a template for character json on the README.

**Comment by nakumiayumu144** [comment]
I mean I want to reset it, because every time I create a new one it still has the same history.
![image](https://user-images.githubusercontent.com/127565115/228570332-8b890f59-a9d6-4ea6-8c67-81eaa1113162.png)

**Comment by Rubiksman78** [comment]
In char_history.txt

**Comment by nakumiayumu144** [comment]
thanks for helping me 👍
